repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.2.2
      hooks:
          # Run the linter.
          - id: ruff
            files: app/\.(py)$
            exclude: ^alembic/
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
            files: \.(py)$
            exclude: ^alembic/
